<!doctype html>
<html class="no-js" lang="">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/css/normalize.css">
    <link rel="import" href="/polymer/bower_components/iron-flex-layout/iron-flex-layout.html">
    <script src="/polymer/bower_components/webcomponentsjs/webcomponents-lite.js"></script>
</head>
<body horizontal class="fullbleed layout horizontal">    
    <?php echo $this->content; ?>
</body>
</html>